apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus2"
  description: "my-quarkus2"
  tags:
    - java
    - quarkus
  links:
    - url: https://codeready-openshift-workspaces.apps.tmp-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/my-quarkus2
      title: Code Ready Workspaces
      icon: web    
  annotations:
    github.com/project-slug: raf-backstage-demo/my-quarkus2
    'backstage.io/kubernetes-id': my-quarkus2
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=my-quarkus2'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "demo-team-a"