apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus2"
  description: "my-quarkus2"
  tags:
    - java
    - quarkus
  links:
    - url: https://che-eclipse-che.apps.cluster-pb2d2.pb2d2.sandbox1409.opentlc.com/#https://github.com/che-incubator/backstage-demo-quarkus2?devfilePath=.devfilev2-theia.yaml
      title: CodeReady Workspaces (Eclipse Theia)
      icon: web
    - url: https://che-eclipse-che.apps.cluster-pb2d2.pb2d2.sandbox1409.opentlc.com/#https://github.com/che-incubator/backstage-demo-quarkus2?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (MS VSCode)
      icon: web    
    - url: https://che-eclipse-che.apps.cluster-pb2d2.pb2d2.sandbox1409.opentlc.com/#https://github.com/che-incubator/backstage-demo-quarkus2?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web    
  annotations:
    github.com/project-slug: che-incubator/backstage-demo-quarkus2
    'backstage.io/kubernetes-id': my-quarkus2
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=my-quarkus2'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "demo-team-a"
