apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "quarkus-build.fullname" . }}-ghcr-pusher"
  labels:
    {{- include "quarkus-build.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ include "quarkus-build.dockerconfigjson" . | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "quarkus-build.fullname" . }}-repo-auth"
  labels:
    {{- include "quarkus-build.labels" . | nindent 4 }}
  annotations:
    build.openshift.io/source-secret-match-uri-1: https://github.com/{{ .Values.github.owner }}/{{ .Values.github.repo_name }}
type: kubernetes.io/basic-auth
data:
  password: "{{ .Values.github.pat | b64enc }}"